[package]
name = "esooli"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "esooli"
path = "src/main.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
tauri = "1.8"

[build-dependencies]
tauri-build = "1.5"
