[package]
name = "esooli"
version = "1.0.0"
edition = "2021"

[dependencies]
tauri = { version = "1.5", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tauri-build = { version = "1.5", default-features = false }
