name: Build Tauri App
on:
    push:
      branches: [ main ]

jobs:
    build:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v4

        - name: Setup Rust
          uses: dtolnay/rust-toolchain@stable

        - name: Create project
          shell: bash
          run: |
            mkdir -p src-tauri/src src/styles src/scripts src-tauri/icons

            cat > src-tauri/Cargo.toml << 'EOF'
            [package]
            name = "esooli"
            version = "1.0.0"
            edition = "2021"

            [dependencies]
            tauri = { version = "1.5", features = [] }
            serde = { version = "1.0", features = ["derive"] }
            serde_json = "1.0"

            [build-dependencies]
            tauri-build = { version = "1.5", features = [] }
            EOF

            cat > src-tauri/build.rs << 'EOF'
            fn main() {
                tauri_build::build()
            }
            EOF

            cat > src-tauri/src/main.rs << 'EOF'
            #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

            fn main() {
                tauri::Builder::default()
                    .run(tauri::generate_context!())
                    .expect("error while running tauri application");
            }
            EOF

            cat > src-tauri/tauri.conf.json << 'EOF'
            {
              "build": {
                "beforeDevCommand": "",
                "beforeBuildCommand": "",
                "devPath": "../src",
                "distDir": "../src",
                "withGlobalTauri": false
              },
              "package": {
                "productName": "Esooli",
                "version": "1.0.0"
              },
              "tauri": {
                "allowlist": {
                  "all": false,
                  "shell": {
                    "all": false,
                    "open": false
                  }
                },
                "bundle": {
                  "active": true,
                  "targets": "all",
                  "identifier": "com.esooli.app",
                  "icon": [
                    "icons/32x32.png",
                    "icons/128x128.png",
                    "icons/icon.ico"
                  ]
                },
                "security": {
                  "csp": null
                },
                "windows": [
                  {
                    "fullscreen": false,
                    "resizable": true,
                    "title": "Esooli",
                    "width": 1200,
                    "height": 800
                  }
                ]
              }
            }
            EOF
            cat > src/index.html << 'EOF'
            <!DOCTYPE html>
            <html lang="ar" dir="rtl">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Esooli</title>
                <style>
                    * { margin: 0; padding: 0; box-sizing: border-box; }
                    body {
                        font-family: 'Segoe UI', sans-serif;
                        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        color: white;
                        height: 100vh;
                        display: flex;
                        flex-direction: column;
                        align-items: center;
                        justify-content: center;
                        text-align: center;
                        padding: 20px;
                    }
                    h1 {
                        font-size: 72px;
                        font-weight: 800;
                        margin-bottom: 20px;
                        text-shadow: 0 4px 20px rgba(0,0,0,0.3);
                    }
                    p {
                        font-size: 24px;
                        opacity: 0.9;
                        margin-bottom: 40px;
                    }
                    .btn {
                        padding: 16px 48px;
                        background: white;
                        color: #667eea;
                        border: none;
                        border-radius: 50px;
                        font-size: 18px;
                        font-weight: 600;
                        cursor: pointer;
                        box-shadow: 0 8px 24px rgba(0,0,0,0.2);
                        transition: all 0.3s;
                    }
                    .btn:hover {
                        transform: translateY(-4px);
                        box-shadow: 0 12px 32px rgba(0,0,0,0.3);
                    }
                </style>
            </head>
            <body>
                <h1>🚀 Esooli</h1>
                <p>تطبيق Tauri احترافي مبني بنجاح!</p>
                <button class="btn">ابدأ الآن</button>
            </body>
            </html>
            EOF

            touch src/styles/main.css
            echo "console.log('Esooli app loaded');" > src/scripts/app.js

            # Create simple icons
            base64 -d > src-tauri/icons/32x32.png << 'ICONEOF'
            iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==
            ICONEOF

            cp src-tauri/icons/32x32.png src-tauri/icons/128x128.png
            cp src-tauri/icons/32x32.png src-tauri/icons/icon.ico

        - name: Build Tauri
          run: |
            cd src-tauri
            cargo build --release

        - name: Upload EXE
          uses: actions/upload-artifact@v4
          with:
            name: EsooliApp-win-x64
            path: src-tauri/target/release/esooli.exe
