name: Build Tauri App
on:
    push:
      branches: [ main ]

jobs:
    build:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v4

        - name: Setup Rust
          uses: dtolnay/rust-toolchain@stable

        - name: Create project files
          shell: bash
          run: |
            mkdir -p src-tauri/src src/styles src/scripts src-tauri/icons

            cat > src-tauri/Cargo.toml << 'EOF'
            [package]
            name = "esooli"
            version = "1.0.0"
            edition = "2021"
            [dependencies]
            tauri = "1.5"
            serde = "1.0"
            [build-dependencies]
            tauri-build = "1.5"
            EOF

            cat > src-tauri/build.rs << 'EOF'
            fn main() { tauri_build::build() }
            EOF

            cat > src-tauri/src/main.rs << 'EOF'
            #![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
            fn main() {
                tauri::Builder::default().run(tauri::generate_context!()).expect("error");
            }
            EOF

            cat > src-tauri/tauri.conf.json << 'EOF'
            {
              "build": {"devPath": "../src", "distDir": "../src"},
              "package": {"productName": "Esooli", "version": "1.0.0"},
              "tauri": {
                "allowlist": {"all": false},
                "bundle": {"identifier": "com.esooli.app", "icon": ["icons/icon.png"]},
                "windows": [{"title": "Esooli", "width": 1200, "height": 800}]
              }
            }
            EOF

            cat > src/index.html << 'EOF'
            <!DOCTYPE html>
            <html>
            <head><meta charset="UTF-8"><title>Esooli</title></head>
            <body style="font-family:sans-serif;padding:40px;background:#f5f5f5">
            <h1 style="color:#0078D4;font-size:48px">Esooli App</h1>
            <p>تطبيق Tauri احترافي</p>
            </body>
            </html>
            EOF

            echo "" > src/styles/main.css
            echo "console.log('ok');" > src/scripts/app.js
            echo "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" > src-tauri/icons/icon.png

        - name: Build Tauri
          run: |
            cd src-tauri
            cargo build --release

        - name: Upload EXE
          uses: actions/upload-artifact@v4
          with:
            name: EsooliApp-win-x64
            path: src-tauri/target/release/esooli.exe
