name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build without bundling
        run: |
          cd src-tauri
          $env:TAURI_SKIP_DEVTOOLS_CHECK="true"
          cargo build --release
        env:
          TAURI_BUNDLE_SKIP: "true"
      - uses: actions/upload-artifact@v4
        with:
          name: EsooliApp
          path: src-tauri/target/release/esooli.exe
